[package]
name = "foundry-compilers-aletheia"
version = "0.0.1"
edition = "2024"

[dependencies]

## Vendored dependencies - See .cargo/config.toml for source substitution

# Mar 8, 2025: https://github.com/foundry-rs/foundry?branch=master#74b8a802
foundry-rs-config = { git = "https://github.com/foundry-rs/foundry", branch = "master", package = "foundry-config" }

# Mar 8, 2025: Linked to vendored directory, v0.13.3
foundry-compilers = { path = "foundry-rs-config/foundry-compilers" }
