[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[dependencies]
"@openzeppelin-contracts" = "5.2.0"
"@prb-math" = "4.1.0"
"@uniswap-v2-periphery" = "1.1.0-beta.0"
"@uniswap-v2-core" = "1.0.1"

[soldeer]
# whether Soldeer manages remappings
remappings_generate = false
# whether Soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
