[alias]
e = "run --example"
tc = "test -- --nocapture"

[source."git+https://github.com/foundry-rs/foundry?tag=nightly-96c40b6ad6ca444e52520d1ee5e7e84d8aa08b22"]
git = "https://github.com/foundry-rs/foundry"
tag = "nightly-96c40b6ad6ca444e52520d1ee5e7e84d8aa08b22"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "foundry-rs-config"
