[alias]
e = "run --example"
tc = "test -- --nocapture"

[source."git+https://github.com/foundry-rs/foundry?branch=master"]
git = "https://github.com/foundry-rs/foundry"
branch = "master"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "foundry-rs-config"
