on: [push, pull_request, workflow_dispatch]

name: Foundry Compilers Aletheia

concurrency:
  group: ci-${{ github.ref }}-cargo
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Install Rust Nightly (2025-01-01)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2025-01-01
          override: true

      - name: Checkout Submodules
        run: git submodule update --init --recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install JS Dependencies
        run: |
          cd test-configs/hardhat-basic
          npm install
          npm install --save-dev
          cd ../../

      - name: Checkout Sources
        uses: actions/checkout@v4

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: |
          ls test-configs/hardhat-basic
          pwd
          cargo build
          cargo test -- --nocapture
